### ISSUE TITLE
version 0.0.19 not working

### ISSUE THREAD

**Issue by lacazeto** [parcelLab/danger-plugin-js#47]
When  `npm i -D @parcellab/danger-plugin`, npm is installing package version 0.0.19 which does not work as it is missing some src files.

I had to manually pin the 0.0.18 version when adjusting the PR for workflows the pL-dev-bot created once we enabled our Repository through the parcelLab/.github.

Example: https://github.com/parcelLab/rfc-frontend-arch/actions/runs/2917301052

**Comment by darioblanco** [comment]
Thanks for the report @lacazeto , it should be fixed now!
